import type { Metadata } from "next";
import { Geist, Geist_Mono, Open_Sans } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import Link from "next/link";

const openSans = Open_Sans({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-opensans',
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${openSans.variable} antialiased`}
      >
        <Toaster position="top-right" />
        <div className="min-h-screen flex flex-col bg-gray-50">
      <header className="border-b bg-white">
        <div className="max-w-5xl mx-auto py-4 px-4 flex items-center justify-between">
          <h1 className="text-xl font-semibold">Mini Bit.ly</h1>
          <span className="text-xs text-gray-500">MERN URL Shortener</span>
        </div>
      </header>
      <main className="flex-1 max-w-5xl mx-auto w-full px-4 py-6">
        {children}
      </main>
      <footer className="border-t bg-white">
        <div className="max-w-5xl mx-auto py-3 px-4 text-xs text-gray-500 flex justify-between">
          <span>© {new Date().getFullYear()} Raeyan</span>
         <Link
      href="/healthz"
      className="text-blue-600 hover:underline"
    >
      System Health
    </Link>
        </div>
      </footer>
    </div>
      </body>
    </html>
  );
}
